version: "3"
services:
  rag-chat:
    image: jianshao/rag-chat-demo:${image_ver}
    container_name: rag-chat
    restart: unless-stopped
    environment:
      - CHROMA_DB_DIR=/home/devel/chroma
      - DATA_ROOT_DIR=/home/devel/data
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
    volumes:
      - ${CHROMA_DB_DIR}:/home/devel/chroma
      - ${DATA_ROOT_DIR}:/home/devel/data
    ports:
      - 5000:5000
    extra_hosts:
      - host.docker.internal:host-gateway
