version: "3"
services:
  rag-chat:
    image: jianshao/rag-chat-demo:${image_ver}
    container_name: rag-chat
    restart: unless-stopped
    environment:
      - https_proxy=${https_proxy}
      - CHROMA_BASE_DIR=/home/devel/chroma
      - DATA_BASE_DIR=/home/devel/data
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - ${HOME}/.config:/home/devel/.config
      - ${CHROMA_BASE_DIR}:/home/devel/chroma
      - ${DATA_BASE_DIR}:/home/devel/data
    ports:
      - 5000:5000
    extra_hosts:
      - host.docker.internal:host-gateway
