services:
  rag-chat:
    image: jianshao/rag-chat-demo:${image_ver}
    container_name: rag-chat
    restart: unless-stopped
    environment:
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - CHROMA_BASE_DIR=/home/devel/chroma
      - DATA_BASE_DIR=/home/devel/data
      - MODEL_PROVIDER=${MODEL_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_BASE_URL=${OPENAI_API_BASE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_HOST=${OLLAMA_HOST:-host.docker.internal}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
    volumes:
      - ${HOME}/.config:/home/devel/.config
      - ${CHROMA_BASE_DIR}:/home/devel/chroma
      - ${DATA_BASE_DIR}:/home/devel/data
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
